@ChatApp_Server_HostAddress = http://localhost:7800

POST {{ChatApp_Server_HostAddress}}/api/auth/login
Accept: application/json

{
  "email": "mot@gmail.com",
  "password": "123"
}
###
GET {{ChatApp_Server_HostAddress}}